import type { Metadata } from "next";
import { Figtree, Urbanist } from "next/font/google";
import "./globals.css";

const urbanist = Urbanist({
    subsets: ["latin"],
    variable: "--font-urbanist",
});

const figtree = Figtree({
    subsets: ["latin"],
    variable: "--font-figtree",
});

export const metadata: Metadata = {
    title: "Fame Tonic",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${urbanist.variable} ${figtree.variable} container mx-auto antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
